### PR TITLE
ci: wire up support for Win32

### PR DESCRIPTION
**Pull request by pks-t**
Wire up support for testing against Win32 in our CI. This is done by migrating from Makefiles to CMake, which is preinstalled on all GitHub runner images and thus way easier to use.

### CODE REVIEW

**Comment by pks-t** [comment]
Depends on https://github.com/clar-test/clar/pull/99 due to compiler errors with MSYS.

**Comment by pks-t** [comment]
Rebased on top of #99 to fix compilation with MinGW, so things are working now with some additional commits on top.

**Review by dscho — APPROVED** [review]
Looks good to me!

**Comment by ethomson** [comment]
What's the rationale for the `uintmax_t` change? Is this some `WIN32` being ambiguous between MSVC and MinGW or something?

**Comment by pks-t** [comment]
@ethomson It's mostly about it not being portable between platforms, and this is getting hit in Windows builds. We could likely work around this somehow with more preprocessor magic. But I think that the more reasonable approach here is to drop it and instead use PRIuMAX and PRIdMAX, which are portable. It saves us some pain and is also conceptually the right approach because it gives us the maximum representable integers.

I've got another patch series queued up where I'll expand on this a bit by introducing type-safe wrappers that always use `uintmax_t` and `intmax_t`.

**Comment by ethomson** [comment]
> It saves us some pain and is also conceptually the right approach because it gives us the maximum representable integers.

I'm not super convinced about the concepts, but I'm also not going to block on a relatively small change. 

But if we're aiming for conceptual correctness, then let's change the decl itself to `uintmax_t` so that we make it consistent and we're not just casting from `size_t` to `uintmax_t`.

**Comment by pks-t** [comment]
> But if we're aiming for conceptual correctness, then let's change the decl itself to uintmax_t so that we make it consistent and we're not just casting from size_t to uintmax_t.

@ethomson Which decls are you referring to specifically? Do you mean the `cl_assert_equal_i()` and similar ones? We don't actually have a variant for `size_t` there, only for plain integers.

**Comment by ethomson** [comment]
This one - https://github.com/clar-test/clar/pull/100/files#diff-1eac78a6ee4c934fe040dcb4bcb60485e71c1f8fd01ae3fb7b084bdd65264933R28 - let's make `line_number` a `uintmax_t`

**Comment by pks-t** [comment]
@ethomson Ah, that one. Adjusted it now :+1:

**Comment by pks-t** [comment]
Rebased with some smallish fixups that I made while working on the clar selftests in #102. @ethomson I consider this PR to be ready now, but please let me know in case you think there's anything missing in here.

**Comment by ethomson** [comment]
Thanks!

**Pull request merged**
